### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by ArlenCHEN** [edomel/ImplicitVF#1]
Dear authors,

Thanks for the awesome work! When will you release the code?

**Comment by edomel** [comment]
Hi, thank you for your interest in the work! I'm sorry for the delay in releasing the code.
However, I'm happy to tell you we will be releasing it by the end of the month!

**Comment by edomel** [comment]
I am sorry for the further delay, I am working to try and release the code as soon as possible

**Comment by edomel** [comment]
The code is now available. For any problem, feel free to raise further issues.
